{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "01361a9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The Amazon Resource Name (ARN) of the role used for this demo is: arn:aws:iam::886035371869:role/torchserve-workshop-SageMakerAPIExecutionRole\n",
      "The name of the role used for this demo is: torchserve-workshop-SageMakerAPIExecutionRole\n"
     ]
    }
   ],
   "source": [
    "import sagemaker\n",
    "\n",
    "sagemaker_session = sagemaker.Session()\n",
    "role = sagemaker.get_execution_role()\n",
    "role_name = role.split([\"/\"][-1])\n",
    "print(f\"The Amazon Resource Name (ARN) of the role used for this demo is: {role}\")\n",
    "print(f\"The name of the role used for this demo is: {role_name[-1]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3e9eff3c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sagemaker.pytorch import PyTorch\n",
    "\n",
    "estimator = PyTorch(\n",
    "    base_job_name=\"BRAD-pytorch-smdataparallel-mnist\",\n",
    "    source_dir=\"code\",\n",
    "    entry_point=\"train_pytorch_smdataparallel_mnist.py\",\n",
    "    role=role,\n",
    "    framework_version=\"1.8.1\",\n",
    "    py_version=\"py36\",\n",
    "    # For training with multinode distributed training, set this count. Example: 2\n",
    "    instance_count=3,\n",
    "    # For training with p3dn instance use - ml.p3dn.24xlarge, with p4dn instance use - ml.p4d.24xlarge\n",
    "    instance_type=\"ml.p3.16xlarge\",\n",
    "    sagemaker_session=sagemaker_session,\n",
    "    # Training using SMDataParallel Distributed Training Framework\n",
    "    distribution={\"smdistributed\": {\"dataparallel\": {\"enabled\": True}}},\n",
    "    debugger_hook_config=False,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "78bb4200",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-06-15 01:26:17 Starting - Starting the training job...\n",
      "2021-06-15 01:26:41 Starting - Launching requested ML instancesProfilerReport-1623720377: InProgress\n",
      "............\n",
      "2021-06-15 01:28:41 Starting - Preparing the instances for training.........\n",
      "2021-06-15 01:30:01 Downloading - Downloading input data\n",
      "2021-06-15 01:30:01 Training - Downloading the training image.......................\u001b[34mbash: cannot set terminal process group (-1): Inappropriate ioctl for device\u001b[0m\n",
      "\u001b[34mbash: no job control in this shell\u001b[0m\n",
      "\u001b[34m2021-06-15 01:33:58,292 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training\u001b[0m\n",
      "\u001b[34m2021-06-15 01:33:58,370 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:01,466 sagemaker_pytorch_container.training INFO     Invoking SMDataParallel\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:01,467 sagemaker_pytorch_container.training INFO     Invoking user training script.\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,114 sagemaker-training-toolkit INFO     Starting MPI run as worker node.\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,114 sagemaker-training-toolkit INFO     Creating SSH daemon.\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,118 sagemaker-training-toolkit INFO     Waiting for MPI workers to establish their SSH connections\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,118 sagemaker-training-toolkit INFO     Network interface name: eth0\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,118 sagemaker-training-toolkit INFO     Host: ['algo-1']\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,122 sagemaker-training-toolkit INFO     instance type: ml.p3.16xlarge\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,201 sagemaker-training-toolkit INFO     Invoking user script\n",
      "\u001b[0m\n",
      "\u001b[34mTraining Env:\n",
      "\u001b[0m\n",
      "\u001b[34m{\n",
      "    \"additional_framework_parameters\": {\n",
      "        \"sagemaker_distributed_dataparallel_enabled\": true,\n",
      "        \"sagemaker_distributed_dataparallel_custom_mpi_options\": \"\",\n",
      "        \"sagemaker_instance_type\": \"ml.p3.16xlarge\"\n",
      "    },\n",
      "    \"channel_input_dirs\": {},\n",
      "    \"current_host\": \"algo-1\",\n",
      "    \"framework_module\": \"sagemaker_pytorch_container.training:main\",\n",
      "    \"hosts\": [\n",
      "        \"algo-1\"\n",
      "    ],\n",
      "    \"hyperparameters\": {},\n",
      "    \"input_config_dir\": \"/opt/ml/input/config\",\n",
      "    \"input_data_config\": {},\n",
      "    \"input_dir\": \"/opt/ml/input\",\n",
      "    \"is_master\": true,\n",
      "    \"job_name\": \"BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432\",\n",
      "    \"log_level\": 20,\n",
      "    \"master_hostname\": \"algo-1\",\n",
      "    \"model_dir\": \"/opt/ml/model\",\n",
      "    \"module_dir\": \"s3://sagemaker-us-east-1-886035371869/BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432/source/sourcedir.tar.gz\",\n",
      "    \"module_name\": \"train_pytorch_smdataparallel_mnist\",\n",
      "    \"network_interface_name\": \"eth0\",\n",
      "    \"num_cpus\": 64,\n",
      "    \"num_gpus\": 8,\n",
      "    \"output_data_dir\": \"/opt/ml/output/data\",\n",
      "    \"output_dir\": \"/opt/ml/output\",\n",
      "    \"output_intermediate_dir\": \"/opt/ml/output/intermediate\",\n",
      "    \"resource_config\": {\n",
      "        \"current_host\": \"algo-1\",\n",
      "        \"hosts\": [\n",
      "            \"algo-1\"\n",
      "        ],\n",
      "        \"network_interface_name\": \"eth0\"\n",
      "    },\n",
      "    \"user_entry_point\": \"train_pytorch_smdataparallel_mnist.py\"\u001b[0m\n",
      "\u001b[34m}\n",
      "\u001b[0m\n",
      "\u001b[34mEnvironment variables:\n",
      "\u001b[0m\n",
      "\u001b[34mSM_HOSTS=[\"algo-1\"]\u001b[0m\n",
      "\u001b[34mSM_NETWORK_INTERFACE_NAME=eth0\u001b[0m\n",
      "\u001b[34mSM_HPS={}\u001b[0m\n",
      "\u001b[34mSM_USER_ENTRY_POINT=train_pytorch_smdataparallel_mnist.py\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_PARAMS={\"sagemaker_distributed_dataparallel_custom_mpi_options\":\"\",\"sagemaker_distributed_dataparallel_enabled\":true,\"sagemaker_instance_type\":\"ml.p3.16xlarge\"}\u001b[0m\n",
      "\u001b[34mSM_RESOURCE_CONFIG={\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"}\u001b[0m\n",
      "\u001b[34mSM_INPUT_DATA_CONFIG={}\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DATA_DIR=/opt/ml/output/data\u001b[0m\n",
      "\u001b[34mSM_CHANNELS=[]\u001b[0m\n",
      "\u001b[34mSM_CURRENT_HOST=algo-1\u001b[0m\n",
      "\u001b[34mSM_MODULE_NAME=train_pytorch_smdataparallel_mnist\u001b[0m\n",
      "\u001b[34mSM_LOG_LEVEL=20\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main\u001b[0m\n",
      "\u001b[34mSM_INPUT_DIR=/opt/ml/input\u001b[0m\n",
      "\u001b[34mSM_INPUT_CONFIG_DIR=/opt/ml/input/config\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DIR=/opt/ml/output\u001b[0m\n",
      "\u001b[34mSM_NUM_CPUS=64\u001b[0m\n",
      "\u001b[34mSM_NUM_GPUS=8\u001b[0m\n",
      "\u001b[34mSM_MODEL_DIR=/opt/ml/model\u001b[0m\n",
      "\u001b[34mSM_MODULE_DIR=s3://sagemaker-us-east-1-886035371869/BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432/source/sourcedir.tar.gz\u001b[0m\n",
      "\u001b[34mSM_TRAINING_ENV={\"additional_framework_parameters\":{\"sagemaker_distributed_dataparallel_custom_mpi_options\":\"\",\"sagemaker_distributed_dataparallel_enabled\":true,\"sagemaker_instance_type\":\"ml.p3.16xlarge\"},\"channel_input_dirs\":{},\"current_host\":\"algo-1\",\"framework_module\":\"sagemaker_pytorch_container.training:main\",\"hosts\":[\"algo-1\"],\"hyperparameters\":{},\"input_config_dir\":\"/opt/ml/input/config\",\"input_data_config\":{},\"input_dir\":\"/opt/ml/input\",\"is_master\":true,\"job_name\":\"BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432\",\"log_level\":20,\"master_hostname\":\"algo-1\",\"model_dir\":\"/opt/ml/model\",\"module_dir\":\"s3://sagemaker-us-east-1-886035371869/BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432/source/sourcedir.tar.gz\",\"module_name\":\"train_pytorch_smdataparallel_mnist\",\"network_interface_name\":\"eth0\",\"num_cpus\":64,\"num_gpus\":8,\"output_data_dir\":\"/opt/ml/output/data\",\"output_dir\":\"/opt/ml/output\",\"output_intermediate_dir\":\"/opt/ml/output/intermediate\",\"resource_config\":{\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"},\"user_entry_point\":\"train_pytorch_smdataparallel_mnist.py\"}\u001b[0m\n",
      "\u001b[34mSM_USER_ARGS=[]\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate\u001b[0m\n",
      "\u001b[34mPYTHONPATH=/opt/ml/code:/opt/conda/bin:/opt/conda/lib/python36.zip:/opt/conda/lib/python3.6:/opt/conda/lib/python3.6/lib-dynload:/opt/conda/lib/python3.6/site-packages\n",
      "\u001b[0m\n",
      "\u001b[34mInvoking script with the following command:\n",
      "\u001b[0m\n",
      "\u001b[34mmpirun --host algo-1 -np 8 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_SINGLENODE=1 -x FI_PROVIDER=efa -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py\n",
      "\n",
      "\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m2021-06-15 01:34:02,469 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:\u001b[0m\n",
      "\u001b[34mCommand \"mpirun --host algo-1 -np 8 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_SINGLENODE=1 -x FI_PROVIDER=efa -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py\"\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34mPrimary job  terminated normally, but 1 process returned\u001b[0m\n",
      "\u001b[34ma non-zero exit code. Per user-direction, the job has been aborted.\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,6]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34mmpirun.real detected that one or more processes exited with non-zero status, thus causing\u001b[0m\n",
      "\u001b[34mthe job to be terminated. The first process to do so was:\n",
      "\n",
      "  Process name: [[41213,1],6]\n",
      "  Exit code:    1\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\n",
      "\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,4]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,2]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,1]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,7]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34mPrimary job  terminated normally, but 1 process returned\u001b[0m\n",
      "\u001b[34ma non-zero exit code. Per user-direction, the job has been aborted.\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,3]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:Traceback (most recent call last):\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    \"__main__\", mod_spec)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 85, in _run_code\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    exec(code, run_globals)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py\", line 7, in <module>\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    main()\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 196, in main\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    run_command_line(args)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/site-packages/mpi4py/run.py\", line 47, in run_command_line\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    run_path(sys.argv[0], run_name='__main__')\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 261, in run_path\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    code, fname = _get_code_from_file(run_name, path_name)\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 236, in _get_code_from_file\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    code = compile(f.read(), fname, 'exec')\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:  File \"train_pytorch_smdataparallel_mnist.py\", line 1\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:    rom __future__ import print_function\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:                 ^\u001b[0m\n",
      "\u001b[34m[1,5]<stderr>:SyntaxError: invalid syntax\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\u001b[34mmpirun.real detected that one or more processes exited with non-zero status, thus causing\u001b[0m\n",
      "\u001b[34mthe job to be terminated. The first process to do so was:\n",
      "\n",
      "  Process name: [[41213,1],6]\n",
      "  Exit code:    1\u001b[0m\n",
      "\u001b[34m--------------------------------------------------------------------------\u001b[0m\n",
      "\n",
      "2021-06-15 01:35:03 Uploading - Uploading generated training model\n",
      "2021-06-15 01:35:03 Failed - Training job failed\n"
     ]
    },
    {
     "ename": "UnexpectedStatusException",
     "evalue": "Error for Training job BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nCommand \"mpirun --host algo-1 -np 8 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_SINGLENODE=1 -x FI_PROVIDER=efa -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py\"\n[1,1]<stderr>:Traceback (most recent call last):\n[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n[1,2]<stderr>:Traceback (most recent call last):\n[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n[1,4]<stderr>:Traceback (most recent call last):\n[1,4]<stderr>:  ",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-5-28be9b2c12b5>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mestimator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, inputs, wait, logs, job_name, experiment_config)\u001b[0m\n\u001b[1;32m    680\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    681\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 682\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    683\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    684\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_compilation_job_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m   1623\u001b[0m         \u001b[0;31m# If logs are requested, call logs_for_jobs.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1624\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"None\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1625\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1626\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1627\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_job\u001b[0;34m(self, job_name, wait, poll, log_type)\u001b[0m\n\u001b[1;32m   3679\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3680\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3681\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TrainingJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3682\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3683\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   3243\u001b[0m                 ),\n\u001b[1;32m   3244\u001b[0m                 \u001b[0mallowed_statuses\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Stopped\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3245\u001b[0;31m                 \u001b[0mactual_status\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3246\u001b[0m             )\n\u001b[1;32m   3247\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Training job BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nCommand \"mpirun --host algo-1 -np 8 --allow-run-as-root --tag-output --oversubscribe -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -mca pml ob1 -mca btl ^openib -mca orte_abort_on_non_zero_status 1 -mca btl_vader_single_copy_mechanism none -mca plm_rsh_num_concurrent 1 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x SMDATAPARALLEL_USE_SINGLENODE=1 -x FI_PROVIDER=efa -x RDMAV_FORK_SAFE=1 -x LD_PRELOAD=/opt/conda/lib/python3.6/site-packages/gethostname.cpython-36m-x86_64-linux-gnu.so smddprun /opt/conda/bin/python3.6 -m mpi4py train_pytorch_smdataparallel_mnist.py\"\n[1,1]<stderr>:Traceback (most recent call last):\n[1,1]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n[1,2]<stderr>:Traceback (most recent call last):\n[1,2]<stderr>:  File \"/opt/conda/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n[1,4]<stderr>:Traceback (most recent call last):\n[1,4]<stderr>:  "
     ]
    }
   ],
   "source": [
    "estimator.fit()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c6f53600",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'s3://sagemaker-us-east-1-886035371869/BRAD-pytorch-smdataparallel-mnist-2021-06-15-01-26-17-432/output/model.tar.gz'"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "model_data = estimator.model_data\n",
    "model_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8f4c7c1d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker\n",
    "\n",
    "role = sagemaker.get_execution_role()\n",
    "\n",
    "from sagemaker.pytorch import PyTorchModel\n",
    "\n",
    "model = PyTorchModel(\n",
    "    model_data=model_data,\n",
    "    source_dir=\"code\",\n",
    "    entry_point=\"inference.py\",\n",
    "    role=role,\n",
    "    framework_version=\"1.6.0\",\n",
    "    py_version=\"py3\",\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8de976fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "predictor = model.deploy(initial_instance_count=1, instance_type=\"ml.m4.xlarge\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f371d30c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from torchvision import datasets, transforms\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "test_set = datasets.MNIST(\n",
    "    \"data\",\n",
    "    download=True,\n",
    "    train=False,\n",
    "    transform=transforms.Compose(\n",
    "        [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]\n",
    "    ),\n",
    ")\n",
    "\n",
    "\n",
    "# Randomly sample 16 images from the test set\n",
    "test_loader = DataLoader(test_set, shuffle=True, batch_size=16)\n",
    "test_images, _ = iter(test_loader).next()\n",
    "\n",
    "# inspect the images\n",
    "import torchvision\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "%matplotlib inline\n",
    "\n",
    "\n",
    "def imshow(img):\n",
    "    img = img.numpy()\n",
    "    img = np.transpose(img, (1, 2, 0))\n",
    "    plt.imshow(img)\n",
    "    return\n",
    "\n",
    "\n",
    "# unnormalize the test images for displaying\n",
    "unnorm_images = (test_images * 0.3081) + 0.1307\n",
    "\n",
    "print(\"Sampled test images: \")\n",
    "imshow(torchvision.utils.make_grid(unnorm_images))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "963c6095",
   "metadata": {},
   "outputs": [],
   "source": [
    "outputs = predictor.predict(test_images.numpy())\n",
    "predicted = np.argmax(outputs, axis=1)\n",
    "\n",
    "print(\"Predictions: \")\n",
    "print(predicted.tolist())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_pytorch_latest_p36",
   "language": "python",
   "name": "conda_pytorch_latest_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
